routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\Auth\{ConfirmPasswordController, ForgetPasswordController};
//use App\Http\Controllers\Auth\ForgetPasswordController;
//use App\Http\Controllers\Auth\LoginController;
//use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ClientsController;
use App\Http\Controllers\InsertionOrdersController;
//use vendor\DataTables;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/reset', [ResetPasswordController::class, 'reset'])->name('password/reset');

Route::post('/reset', [ResetPasswordController::class, 'update'])->name('password.update');
Auth::routes();

Route::group(['middleware' => ['auth','web']], function () {
    
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])
        ->name('home');
   
    Route::resource('users', UsersController::class);
    
    
    Route::get('/clients/getdata', [ClientsController::class, 'getdata'])->name('clients.getdata');
    Route::get('/clients/{client}/showinsertions', [ClientsController::class, 'showinsertions'])->name('clients.showinsertions');
    Route::resource('clients', ClientsController::class);
    
    Route::get('/insertionorders/getdata', [InsertionOrdersController::class, 'getdata'])->name('insertionorders.getdata');
    Route::get('/insertionorders/search', [InsertionOrdersController::class, 'search'])->name('insertionorders.search');
    Route::get('/insertionorders/printio/{client}', [InsertionOrdersController::class, 'printio'])->name('insertionorders.printio');
    Route::get('/insertionorders/webio/{client}', [InsertionOrdersController::class, 'webio'])->name('insertionorders.webio');
    Route::get('/insertionorders/flyerio/{client}', [InsertionOrdersController::class, 'flyerio'])->name('insertionorders.flyerio');
    Route::get('/insertionorders/classifiedio/{client}', [InsertionOrdersController::class, 'classifiedio'])->name('insertionorders.classifiedio');
    Route::get('/insertionorders/{insertionorder}/edit-order-number', [InsertionOrdersController::class, 'edit_order_number'])->name('insertionorders.editordernumber');
    Route::put('/insertionorders/edit-order-number/{insertionorder}', [InsertionOrdersController::class, 'update_order_number'])->name('insertionorders.updateordernumber');
    Route::get('/insertionorders/cancel/{insertionorder}', [InsertionOrdersController::class, 'cancel'])->name('insertionorders.cancel');
    Route::put('/insertionorders/cancel/{insertionorder}', [InsertionOrdersController::class, 'cancelio'])->name('insertionorders.cancelio');
    Route::resource('insertionorders', InsertionOrdersController::class);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home2'); 
    
 });

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\InsertionOrder;

class Client extends Model
{
    use HasFactory;

    public function insertionorders()
    {
        return $this->hasMany(InsertionOrder::class);
    }

}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Client;
use App\Models\InsertionOrder;
use App\Models\User;
use DataTables;
use App\Helper\Helper;
use Illuminate\Support\Facades\Gate;
use App\Mail\ClientUpdateMail;
use Illuminate\Support\Facades\Mail;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$clients = Client::orderby('client_name', 'asc')->get();
       // $clients = Client::with(['id','dti_id','client_name', 'city'])->chunk(100);
        return view('clients.index');
    }
   
    public function getdata(Request $request, Client $ser)
    {
            $input = \Arr::except($request->all(),array('_token', '_method'));
            $data = Client::orderby('client_name')->get();
            
            if(isset($input['client_name'])) {
                $data = Client::where('client_name', 'like', '%'.$input['client_name'].'%')->orderby('client_name')->get();
            }
            if(isset($input['dti_id'])) {
               
                $data = Client::where('dti_id', $input['dti_id'])->orderby('client_name')->get();
            }
         
            return \DataTables::of($data)
                ->addColumn('action', function($data) {
                    $btn = "";
                    if (Gate::allows('sales-only', auth()->user())) {
                        $btn = '<a href="/insertionorders/printio/'. $data->id.'" class="edit btn btn-info btn-sm mx-1" title="Create Print IO"><i class="fas fa-plus-circle"></i> <strong>P</strong></a>';
                        $btn = $btn. '<a href="/insertionorders/webio/'. $data->id.'" class="edit btn btn-info btn-sm mx-1" title="Create Web IO"><i class="fas fa-plus-circle"></i> <strong>W</strong></a>';
                        $btn = $btn. '<a href="/insertionorders/flyerio/'. $data->id.'" class="edit btn btn-info btn-sm mx-1" title="Create Flyer IO"><i class="fas fa-plus-circle"></i> <strong>F</strong></a>';
                        $btn = $btn. '<a href="/insertionorders/classifiedio/'. $data->id.'" class="edit btn btn-info btn-sm mx-1" title="Create Classified IO"><i class="fas fa-plus-circle"></i> <strong>C</strong></a>';
                    }
                    $btn = $btn.'<a href="/clients/' . $data->id .'/edit" class="edit btn btn-primary btn-sm mx-1"><i class="fas fa-edit"></i> Edit</a>';
                    
                    
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'dti_id' => 'nullable',
            'client_name' => 'required',
            'address' => 'required',
            'city' => 'required',
            'province' => 'required',
            'postal_code' => 'required',
            'billing_contact_name' => 'required',
            'billing_contact_email' => 'required|email',
            'billing_contact_phone' => 'required',
            'client_contact_name' => 'nullable',
            'client_contact_phone' => 'nullable',
            'client_contact_email' => 'nullable'
        ]);

        $client = new Client;
        $client->dti_id = $request->input('dti_id');
        $client->client_name = $request->input('client_name');
        $client->address = $request->input('address');
        $client->city = $request->input('city');
        $client->province = $request->input('province');
        $client->postal_code = $request->input('postal_code');
        $client->billing_contact_name = $request->input('billing_contact_name');
        $client->billing_contact_email = $request->input('billing_contact_email');
        $client->billing_contact_phone = $request->input('billing_contact_phone');
        $client->client_contact_name = $request->input('client_contact_name');
        $client->client_contact_email = $request->input('client_contact_email');
        $client->client_contact_phone = $request->input('client_contact_phone');
        $client->save();

        return redirect('/clients')->with('success', 'Client has been added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $client = Client::find($id);
        //$insertionorders = InsertionOrder::where('client_id', $id);
        return view('clients.show')->with('client', $client);
        //dd('show client stuffs');
    }

    public function showinsertions(Request $request, $id)
    {
         
        $user_id = auth()->id();
       
        if (Gate::allows('front-only', auth()->user())) {
            $user = User::find($user_id);
            $email = $user->email;
            $q = InsertionOrder::select([
                'client_id',
                'insertion_orders.id',
                'order_number',
                'order_type',
                'caption_line',
                'total',
                'print_start_date_0',
                'print_end_date_0',
                'web_start_date',
                'web_end_date',
                'classified_start_date',
                'classified_end_date',
                'cancel',
                'users.name',
            ])  ->join('users','users.id','=','insertion_orders.user_id')
                ->where('users.office_admin_email', $email)
                ->where('client_id', $id); 
                
        } elseif(Gate::allows('admin-only', auth()->user())){ 
            $q = InsertionOrder::select([
                'client_id',
                'id',
                'user_id',
                'order_number',
                'order_type',
                'total',
                'print_start_date_0',
                'print_end_date_0',
                'web_start_date',
                'web_end_date',
                'classified_start_date',
                'classified_end_date',
                'cancel',
            ])->where('client_id', $id); 
        } else {
            $q = InsertionOrder::select([
                'client_id',
                'id',
                'user_id',
                'order_number',
                'order_type',
                'total',
                'print_start_date_0',
                'print_end_date_0',
                'web_start_date',
                'web_end_date',
                'classified_start_date',
                'classified_end_date',
                'cancel',
            ])->where('user_id', '!=', '1')->where('client_id', $id);  // show all orders except Admin's 
        }
       
       // dd($q);

        if ($dti_id = $request->input('dti_id')) {
            $q->wherehas('client', function($query)Use($dti_id){ $query->where('dti_id', $dti_id); });
        } elseif ($client_name = $request->input('client_name')) {
            $q->wherehas('client', function($query)Use($client_name){ $query->where('client_name','like', '%'.$client_name.'%'); });
        }
        
        $insertion_orders = $q->with('client:id,client_name')->get()->map(function($order){ 
            // this maps client_name into data-set
            $order->client_name = $order->client->client_name;
            return $order;

         });

        return \DataTables::of($insertion_orders)
            ->addColumn('action', function($data) {
                if (Gate::allows('front-only', auth()->user())) {
                    $btn = '<a href="'. route('insertionorders.editordernumber', $data->id).'"><button class="btn btn-sm btn-primary"><i class="fas fa-plus-circle"></i> Update Order #</button></a>';
                } else {
                    if (($data->order_number != null) && ($data->cancel != true)) {
                        $user_id = auth()->id();
                        if ($user_id != $data->user_id) { // if the user does not match don't allow them to edit.
                            $btn = '<button class="edit btn btn-primary btn-sm mx-1" disabled><i class="fas fa-edit"></i> Edit</button>';
                        } else {
                            $btn = '<a href="'.route('insertionorders.edit', $data->id).'" class="edit btn btn-primary btn-sm mx-1"><i class="fas fa-edit"></i> Edit</a>';
                        }
                    } else {
                        $btn = '<button class="edit btn btn-primary btn-sm mx-1" disabled><i class="fas fa-edit"></i> Edit</button>';
                    }
                    $btn = $btn.'<a href="/insertionorders/'. $data->id.'/edit?clone=y" class="edit btn btn-warning btn-sm mx-1" ><i class="far fa-copy"></i> Clone IO</a>';  
                }
                return $btn;
            })
            ->addColumn('io_type', function($data){
                if ($data->order_type == "1") {
                    $order_type = "Print";
                } else if ($data->order_type == "2") {
                    $order_type = "Web";
                } else if ($data->order_type == "3") {
                    $order_type = "Flyer";
                } else if ($data->order_type == "4") {
                    $order_type = "Classified";
                } else {
                    $order_type = "Not Found: " . $data->order_type;
                }
                return $order_type;
            })
            ->addColumn('start_date', function($data){
                if ($data->print_start_date_0 == "") {
                    if ($data->web_start_date == "") { // if there is no webdate then io is a classified

resources/views/clients/create.blade.php
@extends('layouts.dashboard')

@section('content')
@section('title', 'Create Client :: Dashboard')
    <div >
        <h1>Add Client</h1>    
        <p>&nbsp;</p>
    </div> 

    <div class="container">
        <form action="/clients" method="POST">
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="dti_id">DTI ID</label>
                    <input type="text" class="form-control" name="dti_id" value="{{ old('dti_id') }}" placeholder="DTI ID">
                    <small id="dti_idHelp" class="form-text text-muted">You can leave this blank if this is a brand new client</small>
                    @if ($errors->has('dti_id'))
                    <div class="text-danger">
                        {{ $errors->first('dti_id') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="client_name">Company/Client Name</label>
                    <input type="text" class="form-control" name="client_name" value="{{ old('client_name') }}" placeholder="Company/Client Name">
                    @if ($errors->has('client_name'))
                    <div class="text-danger">
                        {{ $errors->first('client_name') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" name="address" value="{{ old('address') }}" placeholder="Address">
                    @if ($errors->has('address'))
                    <div class="text-danger">
                        {{ $errors->first('address') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="city">City</label>
                    <input type="city" class="form-control" name="city" :error="form.errors.city" value="{{ old('city') }}" placeholder="City">
                    @if ($errors->has('city'))
                    <div class="text-danger">
                        {{ $errors->first('city') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-4">
                    <label for="province">Province</label>
                    <input type="text" class="form-control" name="province" value="{{ old('province') }}" placeholder="Province">
                    @if ($errors->has('province'))
                    <div class="text-danger">
                        {{ $errors->first('province') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-2">
                    <label for="postal_code">Postal Code</label>
                    <input type="text" class="form-control" name="postal_code" value="{{ old('postal_code') }}" placeholder="Postal Code">
                    @if ($errors->has('city'))
                    <div class="text-danger">
                        {{ $errors->first('postal_code') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <label>Billing Contact Information:</label>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="billing_contact_name">Name</label>
                    <input type="text" class="form-control" name="billing_contact_name" value="{{ old('billing_contact_name') }}" placeholder="Billing Contact Name">
                    @if ($errors->has('billing_contact_name'))
                    <div class="text-danger">
                        {{ $errors->first('billing_contact_name') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-4">
                    <label for="billing_contact_email">Email</label>
                    <input type="email" class="form-control" name="billing_contact_email" value="{{ old('billing_contact_email') }}" placeholder="Billing Contact Email">
                    @if ($errors->has('billing_contact_email'))
                    <div class="text-danger">
                        {{ $errors->first('billing_contact_email') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-4">
                    <label for="billing_contact_phone">Phone</label>
                    <input type="text" class="form-control" name="billing_contact_phone" value="{{ old('billing_contact_phone') }}" placeholder="Billing Contact phone">
                    @if ($errors->has('billing_contact_phone'))
                    <div class="text-danger">
                        {{ $errors->first('billing_contact_phone') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <label>Client Contact Information:</label>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="client_contact_name">Name</label>
                    <input type="text" class="form-control" name="client_contact_name" value="{{ old('client_contact_name') }}" placeholder="Client Contact Name">
                    @if ($errors->has('client_contact_name'))
                    <div class="text-danger">
                        {{ $errors->first('client_contact_name') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-4">
                    <label for="client_contact_email">Email</label>
                    <input type="email" class="form-control" name="client_contact_email" value="{{ old('client_contact_email') }}" placeholder="Client Contact Email">
                    @if ($errors->has('client_contact_email'))
                    <div class="text-danger">
                        {{ $errors->first('client_contact_email') }}
                      </div>
                    @endif
                </div>
                <div class="form-group col-md-4">
                    <label for="client_contact_phone">Phone</label>
                    <input type="text" class="form-control" name="client_contact_phone" value="{{ old('client_contact_phone') }}" placeholder="Client Contact phone">
                    @if ($errors->has('client_contact_phone'))
                    <div class="text-danger">
                        {{ $errors->first('client_contact_phone') }}
                      </div>
                    @endif
                </div>
            </div>
            <div class="form-row">
                <button type="submit" class="btn btn-primary">Add Client</button>
            </div>
        </form>
    </div>
   <p>&nbsp;</p><p>&nbsp;</p>
   <p>&nbsp;</p><p>&nbsp;</p>
@stop



@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/clients/index.blade.php
@extends('layouts.dashboard')

@section('content')
@section('title', 'Client Database :: Dashboard')
@section('plugins.Datatables', true)
<div class="float-left">
    <h1>Client Database</h1>    
    <p>&nbsp;</p>
</div> 
<div class="float-right">
    <a href="/clients/create"><button type="button" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add Client</button></a>
</div>   
<div style="clear:both"></div>
<div class="card">
    <div class="card-body">
        <div class="card-title">
            Advance Searching
        </div>
        <form method="GET" id="search-form">
            <div class="row">
                <div class="col-lg-3">
                    <input type="text" class="form-control adv-search-input" placeholder="Client Name" name="client_name" value="{{ (isset($_GET['client_name']) && $_GET['client_name'] != '')?$_GET['client_name']:'' }}">
                </div>
                <div class="col-lg-3">
                    <input type="text" class="form-control adv-search-input" placeholder="DTI ID" name="dti_id" value="{{ (isset($_GET['dti_id']) && $_GET['dti_id'] != '')?$_GET['dti_id']:'' }}">
                </div>
                <div class="col-lg-12">
                    <hr>
                    <button class="btn btn-success" type="submit" id="extraSearch">Search</button>
                    <a class="btn btn-danger" href="/clients">Reset</a>
                </div>
            </div>
        </form>
    </div>
</div>
    
   <table id="clients-table" class="table table-condensed dataTable no-footer" role="grid" aria-describedby="clients-table_info">
       <thead>
           <tr role="row">
               <th>ID</th>
               <th>DTI ID</th>
               <th>Client Name</th>
               <th>City</th>
               <th>Action</th>

           </tr>
       </thead>
       <tbody>
           
       </tbody>
   </table>

   <p>&nbsp;</p><p>&nbsp;</p>
   <p>&nbsp;</p><p>&nbsp;</p>
@stop

@section('js')
    <script> 
    jQuery(function($) {
       //initiate dataTables plugin
       var myTable = 
       $('#clients-table').DataTable( {
           processing: true,
           serverSide: true,
           bFilter: false,
           responsive: true,
           ordering: false,
           ajax: {
                url: '{{ route('clients.getdata') }}',
                    data: function (d) {
                    d.client_name = $('input[name=client_name]').val();
                    d.dti_id = $('input[name=dti_id]').val();
                }
            },
           columns: [
           {data: 'id', name: 'id'},
           {data: 'dti_id', name: 'DTI ID'},
           {data: 'client_name', name: 'Client Name', width: '30%',
                fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                    if(oData.client_name) {
                        $(nTd).html("<a href='/clients/"+oData.id+"'>"+oData.client_name+"</a>");
                    }
                }
           },
           {data: 'city', name: 'City'},
           {data: 'action', name: 'action', orderable: false, searchable: false, width: '25%'},
           ],
       
       
        });
    });
   
   console.log('Hi!'); </script>
  
@stop

resources/views/clients/show.blade.php
@extends('layouts.dashboard')

@section('content')
@section('title', 'View Client :: Dashboard')
<div >
    <h1>View Client</h1>    
    <p>&nbsp;</p>
</div> 

<div class="container">
    <div class="row">
        <div class="col">
        <h3>{{ $client->client_name }} </h3>
        <label>Account #: {{ $client->dti_id }}</label><br>
        {{ $client->address }}<br>
        {{ $client->city }}, 
        {{ $client->province }}<br>
        {{ $client->postal_code }}
            <br><br>

        </div>
        <div class="col">
            <h3>&nbsp;</h3>
            <label>Billing Contact Details:</label><br>
            {{ $client->billing_contact_name }}<br>
            {{ $client->billing_contact_phone }}<br>
            {{ $client->billing_contact_email }}<br>
            <label>Client Contact Details:</label><br>
            {{ $client->client_contact_name }}<br>
            {{ $client->client_contact_phone }}<br>
            {{ $client->client_contact_email }}<br>
        </div>
        <div class="col">
           <a href="{{ route('clients.edit', $client->id) }}" title="Edit Client"><button class="btn btn-primary"><i class="fas fa-edit"></i>Edit</button></a>
           @if (Gate::allows('sales-only', auth()->user()))
           <a href="{{ route('insertionorders.printio', $client->id) }}" title="Create Print IO"><button class="btn btn-info"><i class="fas fa-fw fa-plus-circle "></i> <strong>P</strong></button></a>
           <a href="{{ route('insertionorders.webio', $client->id) }}" title="Create Web IO"><button class="btn btn-info"><i class="fas fa-fw fa-plus-circle "></i> <strong>W</strong></button></a>
           <a href="{{ route('insertionorders.flyerio', $client->id) }}" title="Create Flyer IO"><button class="btn btn-info"><i class="fas fa-fw fa-plus-circle "></i> <strong>F</strong></button></a>
           <a href="{{ route('insertionorders.classifiedio', $client->id) }}"  title="Create Classified IO"><button class="btn btn-info"><i class="fas fa-fw fa-plus-circle "></i> <strong>C</strong></button></a>
           @endif
        </div>
    </div>
    <div class="row">
        <div class="col">
        <label>Insertion Orders: </label><br>    
        <table id="clients-table" class="table table-condensed dataTable no-footer" role="grid" aria-describedby="clients-table_info">
            <thead>
                <tr role="row">
                    <th>ID</th>
                    <th>Client Name</th>
                    <th>Order Number</th>
                    <th>IO Type</th>
                    <th>Total</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Action</th>
     
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
    
</div>
<div class="row">
    <div class="col">
        <br><br><br>
        <!--<button class="btn btn-danger">Delete Client</button>   This button is not functional-->
    </div>
</div>
</div>

    
@stop

@section('js')
<script> 
    jQuery(function($) {
       //initiate dataTables plugin
       var myTable = 
       $('#clients-table').DataTable( {
           processing: true,
           serverSide: true,
           bFilter: false,
           responsive: true,
           "order": [[ 0, "desc" ]],
           ajax: {
                url: '{{ route('clients.showinsertions', $client->id) }}',
                    data: function (d) {
                    d.client_name = $('input[name=client_name]').val();
                    d.dti_id = $('input[name=dti_id]').val();
                }
            },
            "createdRow": function( row, data, dataIndex){
                if( data['cancel'] ==  `1`){
                    $(row).addClass('cancel');
                }
           },
           columns: [
            {data: 'id', name: 'id',
                    fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                    if(oData.client_name) {
                        $(nTd).html("<a href='/insertionorders/"+oData.id+"'>"+oData.id+"</a>");
                    }
                }
            },
            {data: 'client_name', name: 'Client Name'},
            {data: 'order_number', name: 'Order Number'},
            {data: 'io_type', name: 'Orde Type', 
                fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                    if(oData.client_name) {
                        $(nTd).html("<a href='/insertionorders/"+oData.id+"'>"+oData.io_type+"</a>");
                    }
                }
            },
            {data: 'total',
                render: $.fn.dataTable.render.number( ',', '.', 2 )},
            {data: 'start_date', name: 'Start Date'},
            {data: 'end_date', name: 'End Date'},
            {data: 'action', name: 'action', orderable: false, searchable: false, width: '17%'},
           ],
       
       
        });
    });
   
   console.log('Hi!'); </script>
  
@stop